""" WE ARE CREATING CLASS OBJECTS FOR EACH OF THE COMPONENTS OF THE PIPELINE TO ENFORCE STRICT CUSTOM DATA TYPES TO WHICH THE 
    CLIENT QUERY AND INTERNAL FUNCTION CALLS MUST ADHERE TO
    THESE CLASSES ARE CREATED USING PYDANTIC """

import pydantic

"""THIS CLASS CONSISTS OF THE DATA TYPES REQUIRED FOR PDF LOADING AND CHUNKING 
    1. THE LIST OF CHUNK DATA TYPE IS ESSENTIALLY WHAT WE GET AS THE RESULT OF THE PIPELINE WHEREIN WE GIVE THE PDF URL AND THE 
    PIPELINE CHUNKS IT BASED ON HIERARCHY AND CONTEXT AND RETURNS A LIST OF HUMAN READABLE CHUNKS 
    2. THE SOURCE ID DATA TYPE IS ESSENTIALLY THE NAME OF PDF OR URL FROM WHICH THE LLMSERPA DID THE CHUNKING ON 
    AND LLMSERPA BY DEFAULT RETURNS THE SOURCE ID WHICH IS PDF PATH OR URL OF THE FILE"""
class RAGChunkAndSource(pydantic.BaseModel):
    chunks: list[str]
    source_id: str = None

""" EMBEDDING DATA TYPE RECEIVES A LIST OF CHUNKS AND RETURNS A LIST OF CHUNKS """
class RAGUpsertResult(pydantic.BaseModel):
    No_of_vectors_stored: int


""" UPDATE AND INSERT NEW VECTORS 
    SO OUR UPDATE AND INSERT WILL RETURN THE NUMBER OF CHUNKS THAT HAVE BEEN INGESTED AND STORED IN THE VECTOR DATABASE"""
class RAGQueryResult(pydantic.BaseModel):
    user_query:str
    sources: list[str]
    number_of_chunks_to_be_queried: int


""" A SEPARATE DATA TYPE FOR USER QUERY AS THE USER WILL SUPPLYING US THE QUERY, PDF PATH AND THE NUMBER OF CHUNKS REQUIRED"""
class RAGSearchResult(pydantic.BaseModel):
    contexts_retrieved_from_vectorDB: list[str]
    sources_of_contexts_retrieved: list[str]
    

    



